linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gosec
    - tparallel

linters-settings:
  goimports:
    local-prefixes: github.com/north70/go-template

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor

run:
  timeout: 5m
  tests: true