FROM golang:1.22-alpine

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

WORKDIR /app

# Копируем миграции в контейнер
COPY migrations /app/migrations

CMD ["goose", "-dir", "/app/migrations", "postgres", "${POSTGRES_DSN}", "up"]